name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Проверить код из репозитория

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Build Docker image
        run: |
          # Проверка наличия Dockerfile
          if [ -f Dockerfile ]; then
            echo "Dockerfile найден в текущем каталоге."
          else
            echo "Dockerfile не найден в текущем каталоге. Убедитесь, что он существует."
            exit 1
          fi

          # Сборка Docker-образа
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/bot_hokky:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/bot_hokky:latest

      - name: Deploy Docker image to remote server
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
          BOT_TOKEN_SECRET: ${{ secrets.BOT_TOKEN }}
        run: |
          sshpass -p "$REMOTE_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << EOF
            # Проверка наличия Docker и Docker Compose
            if ! [ -x "$(command -v docker)" ]; then
              echo 'Ошибка: Docker не установлен.' >&2
              exit 1
            fi
            if ! [ -x "$(command -v docker-compose)" ]; then
              echo 'Ошибка: Docker Compose не установлен.' >&2
              exit 1
            fi

            # Pull последней версии Docker-образа
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/bot_hokky:latest

            # Остановка текущих контейнеров и запуск новых
            docker compose down
            docker compose up -d --build
          EOF
