name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Build and deploy using Docker Compose
        env:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
          BOT_TOKEN_SECRET: ${{ secrets.BOT_TOKEN }}
        run: |
          # Архивируем проект, игнорируя изменяющиеся файлы
          tar --exclude='./.git' --exclude='./node_modules' --warning=no-file-changed -czf project.tar.gz .

          # Копируем архив на удаленный сервер
          sshpass -p "$REMOTE_PASSWORD" scp project.tar.gz $REMOTE_USER@$REMOTE_HOST:/root/

          # Подключаемся к серверу и разворачиваем проект
          sshpass -p "$REMOTE_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << EOF
            cd /root
            tar -xzf project.tar.gz
            rm project.tar.gz
            docker-compose down
            docker-compose up -d --build
          EOF

      - name: Cleanup
        run: rm -f project.tar.gz
